// rules/RuleRepository.js
// CRUD for rules stored in a rules_config table.
const db=require("../utils/db");const{v4:uuidv4}=require("uuid");const l=require("../utils/logger");
const T="rules_config";const TTL=60000;var cache=null;var ts=0;
function r2r(r){return{id:r.id,name:r.name,description:r.description||"",enabled:Boolean(r.enabled),priority:Number(r.priority)||0,conditions:typeof r.conditions==="string"?JSON.parse(r.conditions):r.conditions,action:r.action,threshold:r.threshold!=null?Number(r.threshold):void 0,created_at:r.created_at,updated_at:r.updated_at}}
async function ensureTable(){await db.query("CREATE TABLE IF NOT EXISTS "+T+" (id UUID PRIMARY KEY,name VARCHAR(255) NOT NULL,description TEXT DEFAULT X,enabled BOOLEAN DEFAULT true,priority INTEGER DEFAULT 0,conditions JSONB NOT NULL,action VARCHAR(50) NOT NULL CHECK(action IN(XHIGH_RISKX,XWARNINGX,XBLOCKX)),threshold NUMERIC(5,2),created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW())");l.info("db ready")}
async function createRule(d){var id=uuidv4();var n=new Date().toISOString();var r=await db.query("INSERT INTO "+T+"(id,name,description,enabled,priority,conditions,action,threshold,created_at,updated_at)VALUES($1,$2,$3,$4,$5,$6::jsonb,$7,$8,$9,$10)RETURNING*;",[id,d.name,d.description||"",d.enabled!==false,d.priority||0,JSON.stringify(d.conditions),d.action,d.threshold!=null?d.threshold:null,n,n]);inv();return r2r(r.rows[0])}
async function getRuleById(id){var r=await db.query("SELECT*FROM "+T+" WHERE id=$1;",[id]);return r.rows.length?r2r(r.rows[0]):null}
async function getAllRules(op){op=op||{};var sql="SELECT*FROM "+T+" ORDER BY priority DESC,created_at ASC;";var p=[];if(op.enabled!==void 0){sql="SELECT*FROM "+T+" WHERE enabled=$1 ORDER BY priority DESC,created_at ASC;";p.push(op.enabled)}return(await db.query(sql,p)).rows.map(r2r)}
async function updateRule(id,up){var fields=[];var p=[];var idx=1;if(up.name!==void 0){fields.push("name=$"+idx++);p.push(up.name)}if(up.description!==void 0){fields.push("description=$"+idx++);p.push(up.description)}if(up.enabled!==void 0){fields.push("enabled=$"+idx++);p.push(up.enabled)}if(up.priority!==void 0){fields.push("priority=$"+idx++);p.push(up.priority)}if(up.conditions!==void 0){fields.push("conditions=$"+idx+++"::jsonb");p.push(JSON.stringify(up.conditions))}if(up.action!==void 0){fields.push("action=$"+idx++);p.push(up.action)}if(up.threshold!==void 0){fields.push("threshold=$"+idx++);p.push(up.threshold)}if(!fields.length)return getRuleById(id);fields.push("updated_at=$"+idx++);p.push(new Date().toISOString());p.push(id);var r=await db.query("UPDATE "+T+" SET "+fields.join(",")+" WHERE id=$"+idx+" RETURNING*;",p);if(!r.rows.length)return null;inv();return r2r(r.rows[0])}
async function deleteRule(id){var r=await db.query("DELETE FROM "+T+" WHERE id=$1;",[id]);inv();return r.rowCount>0}
async function loadActiveRules(){var n=Date.now();if(cache&&(n-ts)<TTL)return cache;var rules=await getAllRules({enabled:true});cache=rules;ts=n;return rules}
function inv(){cache=null;ts=0}
module.exports={ensureTable,createRule,getRuleById,getAllRules,updateRule,deleteRule,loadActiveRules,invalidate:inv};